### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by uaiz** [HearthSim/Hearthstone-Collection-Tracker#10]
Bought a new pc, no crapware. Win 7 ultimate SP1, installed just the drivers and the updates.
Fresh install of battle.net, hearthstone, HDT and the plugin.
DLL unlocked, plugin enabled, I go for importing from heartstone, it switch to HS window but does nothing. The plugin window still is at the "import from hearthstone" button, if I press again the button happens the same thing.
Tried also running HDT with admin privileges, with HS fullscreen (1920x1080) and with HS on window.
Any suggestion?
Exporting works flawlessly.

**Comment by judge2020** [comment]
Hi,

First, make sure you're running the latest version which is 0.7. You saw it switches to the Hearthstone window but it no longer does that. HCT also does not export (that's part of HDT)

Send a screenshot of what the window looks like after pressing the button please.

**Comment by uaiz** [comment]
I know HCT does not export :)

It's 0.7.
I've also tried 0.6.1 and 0.6 and they immediatly tell me that I've successfully imported, but they don't even switch to the HS window, nor "browse" any of my cards.

I'm using HS in italian (with HDT correctly configured for italian), and I've also tried to switch it to english and to reconfigure HDT for english, but that hasn't worked.

![screenshot_20170208](https://cloud.githubusercontent.com/assets/10634571/22755781/e4019992-ee44-11e6-8fad-767521bfb322.JPG)

I'm an experienced sysadmin, if you need anything "advanced",  just ask :)

**Comment by tobyhage** [comment]
Hello,

I have the same issue. Collection tracker plugin shows version 0.6.8. instead of 0.7.
Maybe that is the problem. I have downloaded from: 

https://github.com/HearthSim/Hearthstone-Collection-Tracker/releases/download/v0.7/HearthstoneCollectionTracker.dll

**Comment by judge2020** [comment]
HCT will no longer flip through pages to load the collection. It will get the data directly from HS just like HDT does.

in **HDT**: Options ->Advanced settings -> importing make sure Auto import new decks is on and it works.

**Comment by tobyhage** [comment]
Thank you. It is working now.

**Comment by judge2020** [comment]
@uaiz are you still experiencing this issue? Try the suggestion above if so.

**Comment by uaiz** [comment]
Mmmm... it works.
Coming from the old version seemed to me that it was not importing (no browsing, no "x cards added"), but it was.
Maybe add a popup that says "nothing new found" or "added x cards?"

**Comment by judge2020** [comment]
That sounds like a great idea. I also forgot to implement actually checking to see if Hearthstone was ready so that will be in 0.8.

Glad it works now.
