### ISSUE TITLE
Error when trying to open Hearthstone Collection Tracker 

### ISSUE THREAD

**Issue by Pand3m0nia** [HearthSim/Hearthstone-Collection-Tracker#13]
HI there,

I get the following errors when trying to open Hearthstone Collection Tracker 0.6.8 (it says 0.7 on the download page) in HDT 1.2.2. I'm not sure if this is caused by the release of Journey to Un'Goro.

![error log](https://cloud.githubusercontent.com/assets/10948053/24828492/9a162a9e-1c5e-11e7-9ff5-54ad9ee3cb11.png)

**Comment by judge2020** [comment]
Hi, this is currently being worked on. For the time being try out this DLL https://github.com/HearthSim/Hearthstone-Collection-Tracker/pull/11#issuecomment-291778012

**Comment by Pand3m0nia** [comment]
Hi there,

I tried the dll in the link and I still get similar errors.

**Comment by CookieCompiler** [comment]
If Collection Tracker throws Errors since HDT 1.2.2., it seems to be a problem with HDT and not the plugin.

**Comment by DiscworldDeath** [comment]
It seems the Collection Tracker folder didn't update to 0.5.2, and remained at 0.5.1, which might've caused the issue.

**Comment by judge2020** [comment]
Please use the 0.7.1
