### ISSUE TITLE
Hemet, Jungle Hunter is Missing

### ISSUE THREAD

**Issue by DiscworldDeath** [HearthSim/Hearthstone-Collection-Tracker#15]
As stated, the card doesn't appear in the collection tracker.

**Comment by judge2020** [comment]
Are you using the Un'Goro patched version? The current main release doesn't include UnGoro at all.

It will hopefully be released soon

**Comment by DiscworldDeath** [comment]
Yes, or I wouldn't be specifying only one card ;-)

**Comment by judge2020** [comment]
No problem :P
