### ISSUE TITLE
embeded  the version number with dll

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Collection-Tracker#16]
https://github.com/HearthSim/Hearthstone-Collection-Tracker/blob/master/Hearthstone%20Collection%20Tracker/Properties/AssemblyInfo.cs
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]

It would be better if you update the version number in AssemblyInfo.cs file when you release the library.

**Comment by judge2020** [comment]
What would benefit from this change? All of HDT referenced the version passed from IPlugin.

**Comment by chucklu** [comment]
@judge2020  when I have multi version of dll in local,I can tell the version of dll by checking the property of the dll file
