### ISSUE TITLE
collection import doesn't work

### ISSUE THREAD

**Issue by algeee** [HearthSim/Hearthstone-Collection-Tracker#17]
i am about to get back to HS. been using HDT before with great success, but now i am facing this problem:
the treasury plugin shows up in plugin manager, but if i click **import from hearthstone** and then **start import**, nothing happens.
it does however recognize if i have the game open or not - if the game is not open, i get a message **not ready**.

i am running 
windows 10 pro 10.0.14393.693
hdt 1.2.2
treasury 0.4.1.0

please help :/

**Comment by MelodicSoul** [comment]
I get the same thing.  clicking start import does nothing.

**Comment by judge2020** [comment]
please see if https://github.com/HearthSim/Hearthstone-Collection-Tracker/releases/tag/v0.7.2 fixes it!

**Comment by algeee** [comment]
hi, 
sadly no difference for me.
odd though that there is such a gap between these versions - treasury is an old name for hdt i guess?

**Comment by judge2020** [comment]
treasury is a way old version

**Comment by judge2020** [comment]
Can't seem to reproduce this bug :/ try running hdt as admin?

**Comment by algeee** [comment]
Hi, yes I did, will try again.

**Comment by algeee** [comment]
no difference agian.
interestingly, in hdt the plugin will show up as 0.7.1 for me.

**Comment by kketover** [comment]
Isn't it true that the plugin no longer needs to click through your entire collection to import your cards? I installed the plugin and hit the import button. While it didn't look like anything occured it now knows my what cards I have and will show what cards are missing from decks I import. I think some users are expecting it to behave like it used to. Maybe a confirmation message when you click import would help tell users that the import is complete.

**Comment by algeee** [comment]
>.< should have thought of that, yea it actually has my collection. fixed it!

**Comment by judge2020** [comment]
Yes, getting confirmation will be worked on soon.

**Comment by judge2020** [comment]
Seems to be fixed and no more issues have been brought up.

**Comment by Eisriese** [comment]
Still got a bug:
I "can import" my collection to the Tracker but when i open my collection in the Tracker it shows me like 5 cards... So there are many cards missing and its not complete imported
