### ISSUE TITLE
Collection Import won't start.

### ISSUE THREAD

**Issue by ThePenitence** [HearthSim/Hearthstone-Collection-Tracker#18]
Sorry if this is not the place for this, or if the answer is up publicly somewhere as I don't see anything on it.
Just got this plugin and nothing happens when I click on "Start Import" the button gets highlighted but nothing happens, I'm on the Collection screen in game while doing this and nothing is happening. I would really love to make use of this plugin so if anyone could tell me what's going wrong here that would be great, thanks~

**Comment by ThePenitence** [comment]
Never mind, I didn't think it would be instant and have no notifications whatsoever.

**Comment by judge2020** [comment]
I'm working on a notification atm.

**Comment by ThePenitence** [comment]
Cool, sorry for making a thread on it, thought it wasn't working when there wasn't any prompt or progress bar or even expected lag from it taking all that data from my collection.
