### ISSUE TITLE
Why isn't Collection Tracker showing all cards?

### ISSUE THREAD

**Issue by Johnny112233** [HearthSim/Hearthstone-Collection-Tracker#19]
Hi,
i just imported my collection several times but when i have a look at it, there are always the same cards missing.
When i look at my Neutral cards, the imported collection starts with Target Dummy and Wisp.
But my first card is Murloc Tinyfin.

For Druid it's the same. I have Innvervate, Moonfire and Claw before Earthen Scales. But the first card shown is Earthen Scale.

Am i doing something wrong or is this intendet to be like this?
I just wanted a nice overview over all of my cards.

When i look at my Collection Tracker Collection, it is switched to "Show All" and "Non-Golden". Even when i try the search bar, it seems, it doesn't even know Murloc Tinyfin.

Thanks for your help!

**Comment by riQQ** [comment]
Collection Tracker is only tracking the cards that are or were obtainable by buying card packs. The cards you mentioned, are either basic cards, that everybody has from the beginning, or adventure cards.
