### ISSUE TITLE
Import updates "Desired" instead of "Card Progress"

### ISSUE THREAD

**Issue by McFork** [HearthSim/Hearthstone-Collection-Tracker#20]
Hello,
I just opened a bunch of packs and imported my collection to the tracker, but I noticed the numbers didn't make sense.
The numbers in "Card Progress" seem to be the ones from my last import, and my latest import modified the "Desired" part.
Here are some screenshot to illustrate the issue:

The numbers in the tracker:
![tracker](https://cloud.githubusercontent.com/assets/4647528/26439887/417e36c4-412a-11e7-85b1-dbd9be361382.JPG)

If I click on "Manage set collection", every card is marked as desired (2, or 1 for legendaries) so it doesn't fit the numbers shown here.

Here is my Hearthstone collection, we can see I indeed have 4 legendaries in Old Gods and not 3:
![collection](https://cloud.githubusercontent.com/assets/4647528/26439946/8780117e-412a-11e7-92f7-63b41a12eb8a.JPG)

And here is a screenshot of my collection on Hearthpwn, just synced using Innkeeper:
![hearthpwn](https://cloud.githubusercontent.com/assets/4647528/26439975/9ebb1f46-412a-11e7-8696-4b6f1e78b1d3.JPG)

We can see that my collection saved on Hearthpwn matches the "Desired" on the tracker.

**Comment by McFork** [comment]
Hello,
I just opened a bunch of packs and imported my collection to the tracker, but I noticed the numbers didn't make sense.
The numbers in "Card Progress" seem to be the ones from my last import, and my latest import modified the "Desired" part.
Here are some screenshot to illustrate the issue:

The numbers in the tracker:
![tracker](https://cloud.githubusercontent.com/assets/4647528/26439887/417e36c4-412a-11e7-85b1-dbd9be361382.JPG)

If I click on "Manage set collection", every card is marked as desired (2, or 1 for legendaries) so it doesn't fit the numbers shown here.

Here is my Hearthstone collection, we can see I indeed have 4 legendaries in Old Gods and not 3:
![collection](https://cloud.githubusercontent.com/assets/4647528/26439946/8780117e-412a-11e7-92f7-63b41a12eb8a.JPG)

And here is a screenshot of my collection on Hearthpwn, just synced using Innkeeper:
![hearthpwn](https://cloud.githubusercontent.com/assets/4647528/26439975/9ebb1f46-412a-11e7-8696-4b6f1e78b1d3.JPG)

We can see that my collection saved on Hearthpwn matches the "Desired" on the tracker.

**Comment by riQQ** [comment]
It's correct. You're card progress states that you have 3 vanilla legendaries and one golden. Desired counts vanilla and golden cards. If you have two vanilla copies and one golden copy of a specific card, it's counted as 2/2 desired for this cards, because you can only put two copies of a non-legendary in a deck.

**Comment by McFork** [comment]
After looking more closely, it seems like the tracker counts golden cards separately from non-golden ones. So it would work as intended, but in a non-instinctive way? Please telle me if I'm wrong.

**Comment by McFork** [comment]
@riQQ Thanks for the reply! That's what I thought after taking another look through my collection.
I think it's a bit counter intuitive personally, but maybe it's just me.
