### ISSUE TITLE
click on "start import" does nothing

### ISSUE THREAD

**Issue by LaurentDe** [HearthSim/Hearthstone-Collection-Tracker#21]
I use Hearthstone-Collection-Tracker for a long time.
But it does work anymore (I don't remember if it is since this release or a previous one)
I checked my version (0.7.2), I tried full screen with best resolution.
Here is my log.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Collection-Tracker/files/1114710/hdt_log.txt)

**Comment by judge2020** [comment]
I'll look into it, likely something with HS update

**Comment by LaurentDe** [comment]
Oh sorry, I guess i am wrong.
By reading https://github.com/HearthSim/Hearthstone-Collection-Tracker/issues/17
i understand that the import is done instantly (and no more by using the search, card by card)
