### ISSUE TITLE
0.7.2 Showing up as 0.7.1 inside HDT

### ISSUE THREAD

**Issue by menace97** [HearthSim/Hearthstone-Collection-Tracker#22]
Double-checked to make sure I had 0.7.2 in the plugins folder
Downloaded 0.7.2 again and placed in plugins folder
Opened up HDT Plugin Options
Reads: "COLLECTION TRACKER 0.7.1"

**Comment by menace97** [comment]
![image](https://user-images.githubusercontent.com/9943387/28337736-dd512624-6bc3-11e7-91b3-a39a2fc728a4.png)

**Comment by judge2020** [comment]
can't fix this but it shows at 8.0 with the newest release
