### ISSUE TITLE
Knights of the Frozen Throne expansion

### ISSUE THREAD

**Issue by adriencarbonne** [HearthSim/Hearthstone-Collection-Tracker#23]
Hello,

Will the plugin require an update for Knights of the Frozen Throne expansion, or is it automatically compatible now?

Thank you

**Comment by judge2020** [comment]
Working on an update now

**Comment by riQQ** [comment]
Update was released: https://github.com/HearthSim/Hearthstone-Collection-Tracker/releases/tag/0.8.0.
