### ISSUE TITLE
Wrong card counts in Knights of the Frozen Throne expansion

### ISSUE THREAD

**Issue by mattrick** [HearthSim/Hearthstone-Collection-Tracker#25]
According to [official site](https://us.battle.net/hearthstone/en/expansions-adventures/knights-of-the-frozen-throne/) there are 135 cards. Collection Tracker shows:
- 98 common
- 72 rare
- 54 epic
- 23 legendary
Total: 247.

As far as I've noticed, compared to list on mentioned site, there should be 23 legendary, 27 epic, 36 rare and 49 commons - exactly half of the numbers shown in plugin.

**Comment by riQQ** [comment]
Cards of which you can put two copies in a deck are counted twice.

**Comment by mattrick** [comment]
Well, that makes sense and I guess - resolves issue.
