### ISSUE TITLE
"Notify on missing cards" issue

### ISSUE THREAD

**Issue by jemiller226** [HearthSim/Hearthstone-Collection-Tracker#3]
Hi,

The collection tracker is notifying me of missing cards when I'm not actually missing the cards. 
![lightningbolt](https://cloud.githubusercontent.com/assets/7871449/21467997/60f4ea08-c9ce-11e6-9bd7-f66c98949f26.PNG)

I double checked, and all of the cards in that list are in my collection. Additionally, Aya Blackpaw is in that deck, not in my collection, and not in the missing card list.

**Comment by judge2020** [comment]
Does HDT correctly export those cards to the game? As far as I can see that is HDT not finding those cards when exporting a deck. Collection fracker will report missing cards when *importing* decks

**Comment by jemiller226** [comment]
It does indeed export correctly.

**Comment by jemiller226** [comment]
I see where the confusion lies. Sorry about that. Here's a pic from an import.

![image](https://cloud.githubusercontent.com/assets/7871449/21510971/5780e688-cc68-11e6-8bab-b871bd4cf43b.png)

I think I see what's happening here, but I'm unsure what the cause is. If I open Collection Tracker, even after having either imported my collection or having added cards by hand, the next time I open Collection Tracker, the collection is blank and I have to do it all over again. It's like nothing is saving.

**Comment by judge2020** [comment]
Please see if this issue still occurs when using [0.6.1](https://github.com/HearthSim/Hearthstone-Collection-Tracker/releases/latest). 0.6.7 was broken as of my mistake.

**Comment by jemiller226** [comment]
- Downloaded new/old version
- Opened HDT
- Imported collection
- It imported tons of cards in blink of eye
- Closed HDT
- Opened HDT
- 0 cards in collection

Is there a log or something I could paste?

**Comment by jemiller226** [comment]
The issue with the Collection Manager not seeing cards in the current collection is fixed in 0.7. Thanks!

The issue I'm having of the collection not being persistent through closing and reopening the program is a different issue that I need to figure out.

**Comment by judge2020** [comment]
Nice to know it was fixed. I will look into #9
