### ISSUE TITLE
Buttons and searchbar stopped working since last HDT update

### ISSUE THREAD

**Issue by DanielZa2** [HearthSim/Hearthstone-Collection-Tracker#31]
Since the last update to Hearthstone Deck Tracker the "show all" / "show only missing" slider, the golden / non-golden slider and the search box stopped working for me. Re-downloading the plugin didn't solve the issue.

I can reach this screen just fine, but anything inside it does not do anything.
![screen](https://user-images.githubusercontent.com/9978272/31709446-c4482a40-b3fa-11e7-8652-2278fcec9269.png)

**Comment by uvut** [comment]
I have the same issue.

**Comment by kstiopin** [comment]
have the same issue

**Comment by Pand3m0nia** [comment]
@judge2020 Could you help perhaps?

**Comment by LilahLys** [comment]
It's still happening.

Was this plugin abandoned?
