### ISSUE TITLE
League Of Explorers Expansion Missing

### ISSUE THREAD

**Issue by pawl** [HearthSim/Hearthstone-Collection-Tracker#4]
It appears the cards from the league of explorers expansion is missing. 

Would the fix for that be similar to this commit?: https://github.com/HearthSim/Hearthstone-Collection-Tracker/commit/4af4af55bad33a36730f93e96776af0595ffabd5

**Comment by riQQ** [comment]
Adventures aren't tracked at the moment.

**Comment by judge2020** [comment]
Tracking adventures wouldn't do much as the only way to lose adventure cards is by manually disenchanting them.

**Comment by pawl** [comment]
I was trying to use this app to get a list of all my hearthstone cards, but that doesn't seem like that's what this is for. So, I ended up making a simple app that does that: https://github.com/pawl/HearthstoneCollectionExporter

Thanks for the quick responses and the examples for how to use HearthMirror.

**Comment by judge2020** [comment]
No problem, and great job on that application!
