### ISSUE TITLE
Can't import from Hearthstone

### ISSUE THREAD

**Issue by ultimate2106** [HearthSim/Hearthstone-Collection-Tracker#5]
So I extracted the dll and put it in the Plugin folder, enabled it in the settings, then went into the settings window of the plugin and pressed import from hearthstone (Hearthstone is open). It says successful but when I click on the Plugin->CollectionTracker Tab and look at the Manager there is still 0 everywhere.. :(

**Comment by judge2020** [comment]
Hi, are you on 0.6.7 and can you take a screenshot of the cards saying 0? I am unable to reproduce this issue at the moment.

**Comment by judge2020** [comment]
Hello again, importing was broken in 0.6.7 (my mistake). Please download 0.6.1(or a version above 0.6.7 if it is out) by going **[here](https://github.com/HearthSim/Hearthstone-Collection-Tracker/releases/latest)**
