### ISSUE TITLE
Collection Tracker tries to write Collection_Default.xml to nonexistent path

### ISSUE THREAD

**Issue by jemiller226** [HearthSim/Hearthstone-Collection-Tracker#9]
Using Process Monitor, I found that Collection Tracker is writing Collection_Default.xml to 

C:\Users\Administrator\AppData\Roaming\HearthstoneDeckTracker\CollectionTracker

This path does not exist on my computer. It is, however, writing config.xml to the correct path:

C:\Users\Admin\AppData\Roaming\HearthstoneDeckTracker\CollectionTracker

This is why, in #3, I thought the issue was that the Collection Manager wasn't tracking my collection at all. That's because it wasn't.

I'm guessing this is due to some weirdness with my copying the files from an old PC to this one. I fixed the issue by altering config.xml manually.

This isn't a bug, maybe an enhancement. It doesn't appear that there's any error checking going on right now. Most programs say when they can't access a path instead of silently failing to work.

**Comment by judge2020** [comment]
I'll add in a message and potential fix for this behavior.

**Comment by judge2020** [comment]
fixed in 0.7.1
